### ISSUE TITLE
KeyError: 'ssh_true' 

### ISSUE THREAD

**Issue by jesscag** [SWOTsimulator/swotsimulator#24]
While running the example an error occurs while processing the grid. Interpolated outputs are not saved. This error happens for every grid made. The traceback calls to line 1166 in rw_data: 

'''
/!\ Error occurred while processing grid /Users/caggiano/swotsimulator/example/swot_output/OREGON_science_grid_p584.nc
  Traceback (most recent call last):
  
  File "/Users/caggiano/opt/anaconda3/envs/myenv/lib/python3.7/site-packages/swotsimulator-3.10-py3.7.egg/swotsimulator/mod_parallel.py", line 153, in _operation_wrapper
    operation(msg_queue, *_args, **kwargs)
  
  File "/Users/caggiano/opt/anaconda3/envs/myenv/lib/python3.7/site-packages/swotsimulator-3.10-py3.7.egg/swotsimulator/run_simulator.py", line 500, in worker_method_swot
    nTeval=nTeval)
  
  File "/Users/caggiano/opt/anaconda3/envs/myenv/lib/python3.7/site-packages/swotsimulator-3.10-py3.7.egg/swotsimulator/mod_run.py", line 325, in create_SWOTlikedata
    model_step.read_var(index=model_data.model_index)
  
  File "/Users/caggiano/opt/anaconda3/envs/myenv/lib/python3.7/site-packages/swotsimulator-3.10-py3.7.egg/swotsimulator/rw_data.py", line 1166, in read_var
    self.input_var['ssh_true'] = self.input_var['ssh_true']*self.SSH_factor
  
KeyError: 'ssh_true'
'''

**Comment by lgaultier** [comment]
Hi, 
Sorry for the delay, can you send me by email your parameter file and one data file so that I can check what is wrong?
I can't reproduce this error

**Comment by jesscag** [comment]
Hello, 
Yes I can do that. I am using the example files provided. 
Thanks
