### ISSUE TITLE
Simulation of noise only fails

### ISSUE THREAD

**Issue by robin-cls** [SWOTsimulator/swotsimulator#28]
I try to simulate only the noise ie. without input model data (file_inputs = None in the configuration), but there was the following error:
`Traceback (most recent call last):
File "/home/ad/robin-cls/.conda/envs/swot_simulator_light/bin/swotsimulator", line 33, in <module>
    sys.exit(load_entry_point('swotsimulator==3.10', 'console_scripts', 'swotsimulator')())
File "/home/ad/robin-cls/.conda/envs/swot_simulator_light/lib/python3.8/site-packages/swotsimulator-3.10-py3.8.egg/swotsimulator/cli.py", line 39, in run_swot_script
 File "/home/ad/robin-cls/.conda/envs/swot_simulator_light/lib/python3.8/site-packages/swotsimulator-3.10-py3.8.egg/swotsimulator/run_simulator.py", line 83, in run_simulator
  File "/home/ad/robin-cls/.conda/envs/swot_simulator_light/lib/python3.8/site-packages/swotsimulator-3.10-py3.8.egg/swotsimulator/mod_run.py", line 138, in load_coordinate_model
UnboundLocalError: local variable 'model_data' referenced before assignment`

I used the params_global.txt file from the examples, with modified paths for inputs and outputs.

**Comment by lgaultier** [comment]
A refactoring of the simulator has been done. The new version is now available at https://github.com/CNES/swot_simulator
